### ISSUE TITLE
How to determine NPC location?

### ISSUE THREAD

**Issue by possibly** [MarkusNemesis/VanillaWoWDB2#15]
This isn't actually an issue, @MarkusNemesis , but this project does something similar to what I am hoping to do with the Lights Hope database. 

I am working in a different framework, but I am using the same world.db and aowow_zones.sql files as you all are. **How do you know which creature is in which zone?** For example, here are three zones:
```
(name, x_min, x_max, y_min, y_max)
"The Barrens", -5143.75, 1612.5, -7510.42, 2622.92
"Mulgore", -3697.92, -272.92, -3089.58, 2047.92
"Desolace", -2545.83, 452.08, -262.5, 4233.33
```
One Adult Plainstrider has these coordinates:
```
(name, position_x, position_y)
"Adult Plainstrider", -2314.87, -113.409
```
This Adult Plainstrider has coordinates that fall into each of these zones, but should only be found in Mulgore!

I see you all have location functions in `includes/game.php`, but I can't quite understand how functions like `coord_tozone` work. Any help is appreciated!

**Comment by MarkusNemesis** [comment]
Hello,

You may want to trace back from the function `function select_zone($at_data, $point)` which checks B/W image masks for what areas cover which parts of zones. This clears up any overlap in the coord checking.

**Comment by possibly** [comment]
`function select_zone($at_data, $point)` was exactly what I was after! I was totally unfamiliar with using B/W image masks in this way -- so thanks for teaching me about that, too!
